var namespace_a_m_p_s_1_1_client_1_1_exceptions =
[
    [ "AlreadyConnectedException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_already_connected_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_already_connected_exception" ],
    [ "AMPSException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_a_m_p_s_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_a_m_p_s_exception" ],
    [ "AuthenticationException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_authentication_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_authentication_exception" ],
    [ "BadFilterException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_bad_filter_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_bad_filter_exception" ],
    [ "BadRegexTopicException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_bad_regex_topic_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_bad_regex_topic_exception" ],
    [ "BufferOverflowException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_buffer_overflow_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_buffer_overflow_exception" ],
    [ "CommandException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_command_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_command_exception" ],
    [ "ConnectionException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_connection_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_connection_exception" ],
    [ "ConnectionRefusedException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_connection_refused_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_connection_refused_exception" ],
    [ "DisconnectedException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_disconnected_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_disconnected_exception" ],
    [ "InvalidProtocolOptionsException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_invalid_protocol_options_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_invalid_protocol_options_exception" ],
    [ "InvalidTopicException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_invalid_topic_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_invalid_topic_exception" ],
    [ "InvalidTransportOptionsException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_invalid_transport_options_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_invalid_transport_options_exception" ],
    [ "InvalidURIException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_invalid_u_r_i_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_invalid_u_r_i_exception" ],
    [ "NameInUseException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_name_in_use_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_name_in_use_exception" ],
    [ "NotEntitledException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_not_entitled_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_not_entitled_exception" ],
    [ "ProtocolException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_protocol_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_protocol_exception" ],
    [ "ProtocolNotFoundException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_protocol_not_found_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_protocol_not_found_exception" ],
    [ "RetryOperationException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_retry_operation_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_retry_operation_exception" ],
    [ "StoreException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_store_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_store_exception" ],
    [ "StreamException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_stream_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_stream_exception" ],
    [ "SubidInUseException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_subid_in_use_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_subid_in_use_exception" ],
    [ "SubscriptionAlreadyExistsException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_subscription_already_exists_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_subscription_already_exists_exception" ],
    [ "TimedOutException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_timed_out_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_timed_out_exception" ],
    [ "TransportException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_transport_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_transport_exception" ],
    [ "TransportTypeException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_transport_type_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_transport_type_exception" ],
    [ "UnknownException", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_unknown_exception.html", "class_a_m_p_s_1_1_client_1_1_exceptions_1_1_unknown_exception" ]
];